server:
  port: 9090

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false    # thymeleaf에 대한 캐시를 남기지 않는다. 운영시에는 true.

  datasource:
    url: jdbc:oracle:thin:@//127.0.0.1:1521/xe
    hikari:
      username: sky
      password: java$!

  jpa:
      hibernate:
          ddl-auto: none  # DDL 쿼리 자동 생성하지 않도록 설정(create:삭제후 생성, update:변경된 스키마 적용)
      properties:
          hibernate:
              '[show_sql]': true                   # 하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력
              '[format_sql]': true                 # 콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현
              '[use_sql_comments]': true     # 디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력
